version: '3.8'

services:
  app:
    build:
      context: . # Thư mục chứa Dockerfile
    container_name: springboot_app
    ports:
      - "8080:8080" # Map cổng container ra cổng host
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306" # Map cổng MySQL container ra host
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql # Lưu trữ dữ liệu MySQL

volumes:
  db_data: # Volume để lưu trữ dữ liệu MySQL
