server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    path: /error
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
jwt:
  expiration: 2592000
  secretKey: "Kwcf1S712QB09llAqg7gcqLCD2i5UQWz5gyzg3jLcUQ="
aws:
  s3:
    bucket-name: oop-bucket
    region: ap-southeast-2
    access-key:
    secret-key:
path-image: https://oop-bucket.s3.ap-southeast-2.amazonaws.com/uploads/